/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoneRouteImport } from './routes/zone'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SuperRouteImport } from './routes/super'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperZonesRouteImport } from './routes/super.zones'
import { Route as SuperSettingsRouteImport } from './routes/super.settings'
import { Route as SuperRidersRouteImport } from './routes/super.riders'
import { Route as SuperRestaurantsRouteImport } from './routes/super.restaurants'
import { Route as SuperOrdersRouteImport } from './routes/super.orders'
import { Route as SuperManagersRouteImport } from './routes/super.managers'
import { Route as SuperFraudRouteImport } from './routes/super.fraud'
import { Route as SuperDeliveriesRouteImport } from './routes/super.deliveries'
import { Route as SuperCustomersRouteImport } from './routes/super.customers'
import { Route as SuperAnalyticsRouteImport } from './routes/super.analytics'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicNotifyWhatsappStatusRouteImport } from './routes/api/public/notify/whatsapp-status'
import { Route as ApiPublicNotifyWhatsappRouteImport } from './routes/api/public/notify/whatsapp'

const ZoneRoute = ZoneRouteImport.update({
  id: '/zone',
  path: '/zone',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperZonesRoute = SuperZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSettingsRoute = SuperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperRidersRoute = SuperRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => SuperRoute,
} as any)
const SuperRestaurantsRoute = SuperRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => SuperRoute,
} as any)
const SuperOrdersRoute = SuperOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SuperRoute,
} as any)
const SuperManagersRoute = SuperManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => SuperRoute,
} as any)
const SuperFraudRoute = SuperFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDeliveriesRoute = SuperDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => SuperRoute,
} as any)
const SuperCustomersRoute = SuperCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAnalyticsRoute = SuperAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicNotifyWhatsappStatusRoute =
  ApiPublicNotifyWhatsappStatusRouteImport.update({
    id: '/api/public/notify/whatsapp-status',
    path: '/api/public/notify/whatsapp-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotifyWhatsappRoute = ApiPublicNotifyWhatsappRouteImport.update({
  id: '/api/public/notify/whatsapp',
  path: '/api/public/notify/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr': typeof QrRoute
  '/restaurants': typeof RestaurantsRoute
  '/rider': typeof RiderRoute
  '/super': typeof SuperRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/zone': typeof ZoneRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/order/$id': typeof OrderIdRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/customers': typeof SuperCustomersRoute
  '/super/deliveries': typeof SuperDeliveriesRoute
  '/super/fraud': typeof SuperFraudRoute
  '/super/managers': typeof SuperManagersRoute
  '/super/orders': typeof SuperOrdersRoute
  '/super/restaurants': typeof SuperRestaurantsRoute
  '/super/riders': typeof SuperRidersRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/zones': typeof SuperZonesRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/notify/whatsapp': typeof ApiPublicNotifyWhatsappRoute
  '/api/public/notify/whatsapp-status': typeof ApiPublicNotifyWhatsappStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr': typeof QrRoute
  '/restaurants': typeof RestaurantsRoute
  '/rider': typeof RiderRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/zone': typeof ZoneRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/order/$id': typeof OrderIdRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/customers': typeof SuperCustomersRoute
  '/super/deliveries': typeof SuperDeliveriesRoute
  '/super/fraud': typeof SuperFraudRoute
  '/super/managers': typeof SuperManagersRoute
  '/super/orders': typeof SuperOrdersRoute
  '/super/restaurants': typeof SuperRestaurantsRoute
  '/super/riders': typeof SuperRidersRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/zones': typeof SuperZonesRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
  '/api/public/notify/whatsapp': typeof ApiPublicNotifyWhatsappRoute
  '/api/public/notify/whatsapp-status': typeof ApiPublicNotifyWhatsappStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/qr': typeof QrRoute
  '/restaurants': typeof RestaurantsRoute
  '/rider': typeof RiderRoute
  '/super': typeof SuperRouteWithChildren
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/zone': typeof ZoneRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/order/$id': typeof OrderIdRoute
  '/super/analytics': typeof SuperAnalyticsRoute
  '/super/customers': typeof SuperCustomersRoute
  '/super/deliveries': typeof SuperDeliveriesRoute
  '/super/fraud': typeof SuperFraudRoute
  '/super/managers': typeof SuperManagersRoute
  '/super/orders': typeof SuperOrdersRoute
  '/super/restaurants': typeof SuperRestaurantsRoute
  '/super/riders': typeof SuperRidersRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/zones': typeof SuperZonesRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/notify/whatsapp': typeof ApiPublicNotifyWhatsappRoute
  '/api/public/notify/whatsapp-status': typeof ApiPublicNotifyWhatsappStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/home'
    | '/location'
    | '/login'
    | '/menu'
    | '/orders'
    | '/privacy-policy'
    | '/qr'
    | '/restaurants'
    | '/rider'
    | '/super'
    | '/terms-and-conditions'
    | '/zone'
    | '/admin/analytics'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/settings'
    | '/order/$id'
    | '/super/analytics'
    | '/super/customers'
    | '/super/deliveries'
    | '/super/fraud'
    | '/super/managers'
    | '/super/orders'
    | '/super/restaurants'
    | '/super/riders'
    | '/super/settings'
    | '/super/zones'
    | '/admin/'
    | '/super/'
    | '/api/public/notify/whatsapp'
    | '/api/public/notify/whatsapp-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/home'
    | '/location'
    | '/login'
    | '/menu'
    | '/orders'
    | '/privacy-policy'
    | '/qr'
    | '/restaurants'
    | '/rider'
    | '/terms-and-conditions'
    | '/zone'
    | '/admin/analytics'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/settings'
    | '/order/$id'
    | '/super/analytics'
    | '/super/customers'
    | '/super/deliveries'
    | '/super/fraud'
    | '/super/managers'
    | '/super/orders'
    | '/super/restaurants'
    | '/super/riders'
    | '/super/settings'
    | '/super/zones'
    | '/admin'
    | '/super'
    | '/api/public/notify/whatsapp'
    | '/api/public/notify/whatsapp-status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/home'
    | '/location'
    | '/login'
    | '/menu'
    | '/orders'
    | '/privacy-policy'
    | '/qr'
    | '/restaurants'
    | '/rider'
    | '/super'
    | '/terms-and-conditions'
    | '/zone'
    | '/admin/analytics'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/settings'
    | '/order/$id'
    | '/super/analytics'
    | '/super/customers'
    | '/super/deliveries'
    | '/super/fraud'
    | '/super/managers'
    | '/super/orders'
    | '/super/restaurants'
    | '/super/riders'
    | '/super/settings'
    | '/super/zones'
    | '/admin/'
    | '/super/'
    | '/api/public/notify/whatsapp'
    | '/api/public/notify/whatsapp-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HomeRoute: typeof HomeRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QrRoute: typeof QrRoute
  RestaurantsRoute: typeof RestaurantsRoute
  RiderRoute: typeof RiderRoute
  SuperRoute: typeof SuperRouteWithChildren
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ZoneRoute: typeof ZoneRoute
  OrderIdRoute: typeof OrderIdRoute
  ApiPublicNotifyWhatsappRoute: typeof ApiPublicNotifyWhatsappRoute
  ApiPublicNotifyWhatsappStatusRoute: typeof ApiPublicNotifyWhatsappStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zone': {
      id: '/zone'
      path: '/zone'
      fullPath: '/zone'
      preLoaderRoute: typeof ZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super/zones': {
      id: '/super/zones'
      path: '/zones'
      fullPath: '/super/zones'
      preLoaderRoute: typeof SuperZonesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/settings': {
      id: '/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof SuperSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/riders': {
      id: '/super/riders'
      path: '/riders'
      fullPath: '/super/riders'
      preLoaderRoute: typeof SuperRidersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/restaurants': {
      id: '/super/restaurants'
      path: '/restaurants'
      fullPath: '/super/restaurants'
      preLoaderRoute: typeof SuperRestaurantsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/orders': {
      id: '/super/orders'
      path: '/orders'
      fullPath: '/super/orders'
      preLoaderRoute: typeof SuperOrdersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/managers': {
      id: '/super/managers'
      path: '/managers'
      fullPath: '/super/managers'
      preLoaderRoute: typeof SuperManagersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/fraud': {
      id: '/super/fraud'
      path: '/fraud'
      fullPath: '/super/fraud'
      preLoaderRoute: typeof SuperFraudRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/deliveries': {
      id: '/super/deliveries'
      path: '/deliveries'
      fullPath: '/super/deliveries'
      preLoaderRoute: typeof SuperDeliveriesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/customers': {
      id: '/super/customers'
      path: '/customers'
      fullPath: '/super/customers'
      preLoaderRoute: typeof SuperCustomersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/analytics': {
      id: '/super/analytics'
      path: '/analytics'
      fullPath: '/super/analytics'
      preLoaderRoute: typeof SuperAnalyticsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/notify/whatsapp-status': {
      id: '/api/public/notify/whatsapp-status'
      path: '/api/public/notify/whatsapp-status'
      fullPath: '/api/public/notify/whatsapp-status'
      preLoaderRoute: typeof ApiPublicNotifyWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify/whatsapp': {
      id: '/api/public/notify/whatsapp'
      path: '/api/public/notify/whatsapp'
      fullPath: '/api/public/notify/whatsapp'
      preLoaderRoute: typeof ApiPublicNotifyWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperAnalyticsRoute: typeof SuperAnalyticsRoute
  SuperCustomersRoute: typeof SuperCustomersRoute
  SuperDeliveriesRoute: typeof SuperDeliveriesRoute
  SuperFraudRoute: typeof SuperFraudRoute
  SuperManagersRoute: typeof SuperManagersRoute
  SuperOrdersRoute: typeof SuperOrdersRoute
  SuperRestaurantsRoute: typeof SuperRestaurantsRoute
  SuperRidersRoute: typeof SuperRidersRoute
  SuperSettingsRoute: typeof SuperSettingsRoute
  SuperZonesRoute: typeof SuperZonesRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAnalyticsRoute: SuperAnalyticsRoute,
  SuperCustomersRoute: SuperCustomersRoute,
  SuperDeliveriesRoute: SuperDeliveriesRoute,
  SuperFraudRoute: SuperFraudRoute,
  SuperManagersRoute: SuperManagersRoute,
  SuperOrdersRoute: SuperOrdersRoute,
  SuperRestaurantsRoute: SuperRestaurantsRoute,
  SuperRidersRoute: SuperRidersRoute,
  SuperSettingsRoute: SuperSettingsRoute,
  SuperZonesRoute: SuperZonesRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HomeRoute: HomeRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QrRoute: QrRoute,
  RestaurantsRoute: RestaurantsRoute,
  RiderRoute: RiderRoute,
  SuperRoute: SuperRouteWithChildren,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ZoneRoute: ZoneRoute,
  OrderIdRoute: OrderIdRoute,
  ApiPublicNotifyWhatsappRoute: ApiPublicNotifyWhatsappRoute,
  ApiPublicNotifyWhatsappStatusRoute: ApiPublicNotifyWhatsappStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
